Repository Knowledge-Management-Capstone/knowledge-management-core, pull requests merged in 2022-11, with the labels that each got.

#149 KMNCORE-143 Added File Upload to Chat
  models/messageModel.js
  socket/index.js
Labels: type:enhancement, priority:high, actual-sp:2

#153 KMNCORE-150 Add Contribution Field
  controllers/documentController.js
  controllers/folderController.js
  controllers/teamController.js
  data/seed.js
  models/contributionModel.js
  models/documentModel.js
Labels: type:enhancement, priority:high, actual-sp:2

#156 KMNCORE-151 Add Multiple Contributions to a Single Document
  controllers/documentController.js
  controllers/folderController.js
Labels: type:enhancement, priority:high, actual-sp:2

#157 KMNCORE-152 Add, Update and Delete Contributions to Existing Documents
  controllers/documentController.js
Labels: type:enhancement, priority:high, actual-sp:2

#158 KMNCORE-154 Add Contribution Field
  utils/queries.js
Labels: type:enhancement, priority:high, actual-sp:5

#161 KMNCORE-160 Add Search By String Function
  config/db.js
  controllers/documentController.js
  controllers/teamController.js
  models/documentModel.js
  models/teamModel.js
  package-lock.json
  routes/documentRoute.js
  routes/teamRoute.js
  utils/queries.js
Labels: type:enhancement, priority:high, actual-sp:1

#165 KMNCORE-164 Removed Unused Database FIelds
  controllers/folderController.js
  controllers/teamController.js
  models/documentModel.js
  utils/queries.js
Labels: type:enhancement, priority:medium, actual-sp:1

#168 KMNCORE-167 Updated Socket CORS Whitelist after Deployment
  socket/index.js
Labels: type:enhancement, priority:high, actual-sp:1

#169 KMNCORE-167 Update Socket CORS Whitelist after Deployment
  socket/index.js
Labels: type:enhancement, priority:high, actual-sp:1
