Repository Knowledge-Management-Capstone/knowledge-management-core, pull requests merged in 2023-01, with the labels that each got.

#175 KMNCORE-173 Add Route for Folder and Document without auth
  controllers/documentController.js
  controllers/folderController.js
  controllers/teamController.js
  models/repositoryModel.js
  routes/documentRoute.js
  routes/folderRoute.js
  routes/teamRoute.js
Labels: type:enhancement, priority:high, actual-sp:1

#178 KMNCORE-176 Add Proposal Document
  controllers/teamController.js
  models/teamModel.js
  utils/queries.js
Labels: type:enhancement, priority:high, actual-sp:1

#180 KMNCORE-179 Updated Route for Searching Document By String
  controllers/documentController.js
Labels: type:enhancement, priority:high, actual-sp:1

#182 KMNCORE-181 update getFolderById To Add Repository In The Result
  controllers/folderController.js
Labels: type:enhancement, priority:medium, actual-sp:1, actual-sp:3

#183 KMNCORE-177 Implement Reference in `getFolderById`
  controllers/folderController.js
  models/documentModel.js
Labels: type:enhancement, priority:high, actual-sp:2

#185 KMNCORE-184 Add `references` Field When Create and Update Document
  controllers/documentController.js
Labels: type:enhancement, priority:high, actual-sp:2

#189 KMNCORE-188 Add Status/Version When Add and Edit Document
  controllers/documentController.js
  controllers/folderController.js
  models/documentModel.js
Labels: type:enhancement, priority:high, actual-sp:1

#191 KMNCORE-190 Implement Not Accepted Account
  controllers/userController.js
Labels: type:enhancement, priority:high, actual-sp:1

#193 KMNCORE-192 Add Reference to getFolderByDocumentId
  controllers/folderController.js
Labels: type:enhancement, priority:high, actual-sp:3

#196 KMNCORE-195 Edit User Profile
  controllers/userController.js
  routes/userRoute.js
Labels: type:enhancement, priority:medium, actual-sp:1
